// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/app/components/header/Header";
import { SessionProvider } from "next-auth/react";
import Footer from "@/app/components/footer/Footer";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} `}>
      <body className="antialiased">
        <SessionProvider>
          {/* Header full width; container bên trong nếu cần */}
          <Header />
          {/* Container ở giữa cho nội dung trang */}
          <div className="bg-[#f5f7fa] ">
            <main className="py-6 mx-auto max-w-[1230px] ">{children}</main>
          </div>
        </SessionProvider>
        <Footer />
      </body>
    </html>
  );
}
